---
- name: install zfsutils-linux
  apt:
    name: zfsutils-linux
    state: present

- name: Format Volume
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "{{ item.device }}"
  loop: "{{ volumes[inventory_hostname] | list }}"
  when: item.fstype != 'zfs'

- name: Mount Volume
  ansible.posix.mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop: "{{ volumes[inventory_hostname] | list }}"
  when: item.fstype != 'zfs'

- name: Setup ZFS zpool
  command: "zpool create -m {{ item.mount_point }} pool{{ idx }} {{ item.device }}"
  args:
    creates: "{{ item.mount_point }}"
  loop: "{{ volumes[inventory_hostname] | list }}"
  loop_control:
    index_var: idx
  when: item.fstype == 'zfs'
