---
####### INFLUXDB #######

- name: Create influxdb Group
  group:
    name: influxdb

- name: Create influxdb User
  user:
    name: influxdb
    group: influxdb

- name: Create Folder
  file:
    path: /mnt/volume/influxdb
    owner: influxdb
    group: influxdb
    state: directory
    mode: 0755

- name: Create symlink
  file:
    path: /var/lib/influxdb
    src: /mnt/volume/influxdb
    state: link
  when: volumes[inventory_hostname] is defined

####### GRAFANA #######

- name: Create grafana Group
  group:
    name: grafana

- name: Create grafana User
  user:
    name: grafana
    group: grafana

- name: Create Folder
  file:
    path: /mnt/volume/grafana
    owner: grafana
    group: grafana
    state: directory
    mode: 0755

- name: Create mount
  file:
    path: /var/lib/grafana
    src: /mnt/volume/grafana
    state: link
  when: volumes[inventory_hostname] is defined

####### DOCKER #######

- name: Create Folder
  file:
    path: /mnt/volume/docker
    owner: root
    group: root
    state: directory
    mode: 0710

- name: Create mount
  file:
    path: /var/lib/docker
    src: /mnt/volume/docker
    state: link
  when: volumes[inventory_hostname] is defined
