---
####### SQUID #######

- name: Create proxy Group
  group:
    name: proxy

- name: Create proxy User
  user:
    name: proxy
    group: proxy

- name: Create Folder
  file:
    path: /mnt/volume/squid
    owner: proxy
    group: proxy
    state: directory
    mode: 0755

- name: Create symlink
  file:
    path: /var/spool/squid
    src: /mnt/volume/squid
    state: link
  when: volumes[inventory_hostname] is defined
