# PostgreSQL
postgresql_objects_users:
  - name: "{{ galaxy_user_name }}"
    password: "{{ galaxy_postgres_password }}"
  - name: telegraf
postgresql_objects_databases:
  - name: "{{ galaxy_db_name }}"
    owner: "{{ galaxy_user_name }}"
postgresql_objects_privileges:
  - database: galaxy
    roles: telegraf
    privs: SELECT
    objs: ALL_IN_SCHEMA
postgresql_pg_hba_conf:
  - host all all {{ galaxy_subnet }} md5
postgresql_conf:
  - listen_addresses: "'*'"
  - port: 5432

# Telegraf
telegraf_plugins_extra:
  monitor_galaxy_queue:
    plugin: "exec"
    config:
      - commands = ["/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery queue-overview --short-tool-id"]
      - timeout = "10s"
      - data_format = "influx"
      - interval = "15s"
  galaxy_uploaded:
    plugin: "exec"
    config:
      - commands = ["/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery upload-gb-in-past-hour"]
      - timeout = "10s"
      - data_format = "influx"
      - interval = "5m"
  galaxy_users_count:
    plugin: "exec"
    config:
      - commands = ["/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery users-count"]
      - timeout = "10s"
      - data_format = "influx"
      - interval = "10m"
  galaxy_jobs_count:
    plugin: "exec"
    config:
      - commands = ["/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery total-jobs"]
      - timeout = "10s"
      - data_format = "influx"
      - interval = "1h"
  galaxy_workflow:
    plugin: "exec"
    config:
      - commands = ["/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery workflow-invocation-status"]
      - timeout = "15s"
      - data_format = "influx"
      - interval = "1m"
  galaxy_workflow_totals:
    plugin: "exec"
    config:
      - commands = ["/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery workflow-invocation-totals"]
      - timeout = "15s"
      - data_format = "influx"
      - interval = "1m"
  postgres_extra:
    plugin: "exec"
    config:
      - commands = [
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-cache-hit",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-index-size",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-index-usage",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-table-bloat",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-table-size",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-unused-indexes",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-vacuum-stats",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-stat-bgwriter",
        "/usr/bin/env PGDATABASE=galaxy /usr/local/bin/gxadmin iquery pg-stat-user-tables",
        ]
      - timeout = "60s"
      - data_format = "influx"
      - interval = "2m"

#TSM
tsm_user: usegalaxy-db
