---
- name: Copy docker-compose.yaml
  copy:
    src: docker-compose.yaml
    dest: ~/docker-compose.yaml

- name: Pull image from Docker Hub
  command: "docker pull jlaperle/geec_web"

- name: Run Docker Compose
  command: "docker compose -f ~/docker-compose.yaml up -d"
