global:
  default_inherits: default

tools:
  default:
    abstract: true
    cores: 1
    mem: cores * 3.8
  toolshed.g2.bx.psu.edu/repos/chemteam/bio3d_pca/bio3d_pca/.*:
    mem: 160
  toolshed.g2.bx.psu.edu/repos/chemteam/bio3d_rmsd/bio3d_rmsd/.*:
    mem: 160
  toolshed.g2.bx.psu.edu/repos/chemteam/bio3d_rmsf/bio3d_rmsf/.*:
    mem: 160
  .*testing.*:
    cores: 2
    mem: cores * 3.8
    rules:
      - id: admin_only_testing_tool
        if: |
          # Only allow the tool to be executed if the user is an admin
          admin_users = app.config.admin_users
          # last line in block must evaluate to a value - which determines whether the TPV if conditional matches or not
          not user or user.email not in admin_users
        fail: Unauthorized. Only admins can execute this tool.

destinations:
  slurm:
    runner: slurm
    max_accepted_cores: 32
    max_accepted_mem: 240
    # max_cores: 2
    # max_mem: 8
    params:
      native_specification: --nodes=1 --ntasks=1 --cpus-per-task={cores} --mem={round(mem*1024)}
      singularity_enabled: true
      singularity_volumes: "$defaults,/cvmfs/data.galaxyproject.org:ro"
    env:
      # Ensuring a consistent collation environment is good for reproducibility.
      LC_ALL: C
      # The cache directory holds the docker containers that get converted
      SINGULARITY_CACHEDIR: /tmp/singularity
      # Singularity uses a temporary directory to build the squashfs filesystem
      APPTAINER_TMPDIR: /tmp
