---
- hosts: nfsservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
    - group_vars/galaxyservers.yml
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - volume
        - nfs
        - setup
    - role: usegalaxy_ca.nfs_server
      tags:
        - nfs
        - setup
    - role: dj-wasabi.telegraf
      tags:
        - setup
        - monitor
    - role: usegalaxy_ca.backup_tsm
      tags:
        - setup
        - backup

- hosts: squidservers
  become: true
  become_user: root
  vars_files:
    - group_vars/terraform.yml
    - group_vars/galaxyservers.yml
    - group_vars/cvmfsservers.yml
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - volume
        - setup
    - role: usegalaxy_ca.squid
      tags:
        - volume
        - cvmfs
        - setup
    - role: laperlej.cvmfs
      tags:
        - setup
        - cvmfs
    - role: dj-wasabi.telegraf
      tags:
        - setup
        - monitor

- hosts: slurmcontrolservers
  become: true
  become_user: root
  vars:
    - slurm_roles: ["controller"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/galaxyservers.yml
  roles:
    - role: usegalaxy_ca.nfs_client
      tags:
        - nfs
        - setup
    - role: usegalaxy_ca.slurm
      tags:
        - slurm
        - setup
    - role: galaxyproject.repos
      tags:
        - slurm
        - setup
    - role: galaxyproject.slurm
      tags:
        - slurm
        - setup
    - role: dj-wasabi.telegraf
      tags:
        - setup
        - monitor

- hosts: slurmexecservers
  become: true
  become_user: root
  vars:
    - slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/galaxyservers.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: usegalaxy_ca.nfs_client
      tags:
        - nfs
        - setup
    - role: usegalaxy_eu.apptainer
      tags:
        - cvmfs
        - setup
    - role: laperlej.cvmfs
      tags:
        - setup
        - cvmfs
    - role: usegalaxy_ca.slurm
      tags:
        - slurm
        - setup
    - role: galaxyproject.repos
      tags:
        - slurm
        - setup
    - role: galaxyproject.slurm
      tags:
        - slurm
        - setup
    - role: dj-wasabi.telegraf
      tags:
        - setup
        - monitor

- hosts: dbservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  pre_tasks:
    - name: install dependencies
      package:
        name: "acl"
      tags:
        - always
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - setup
        - volume
    - role: usegalaxy_ca.postgresql
      tags:
        - setup
        - postgres
    - role: galaxyproject.postgresql
      tags:
        - setup
        - postgres
    - role: usegalaxy_ca.restart_postgres
      tags:
        - setup
        - never
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
      tags:
        - setup
        - postgres
    - role: usegalaxy_ca.gxadmin
      tags:
        - setup
        - monitor
    - role: galaxyproject.gxadmin
      tags:
        - setup
        - monitor
    - role: dj-wasabi.telegraf
      tags:
        - setup
        - monitor
    - role: usegalaxy_ca.backup_pg
      tags:
        - setup
        - postgres
    - role: usegalaxy_ca.backup_tsm
      tags:
        - setup
        - backup

- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    - slurm_roles: ["exec"]
  vars_files:
    - group_vars/secret.yml
    - group_vars/slurm.yml
    - group_vars/cvmfsclient.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: usegalaxy_ca.nfs_client
      tags:
        - nfs
        - setup
    - role: usegalaxy_ca.slurm
      tags:
        - slurm
        - setup
    - role: galaxyproject.repos
      tags:
        - slurm
        - setup
    - role: galaxyproject.slurm
      tags:
        - slurm
        - setup
    - role: usegalaxy_eu.apptainer
      tags:
        - cvmfs
        - setup
    - role: galaxyproject.tusd
      tags:
        - tusd
        - setup
    - role: galaxyproject.galaxy
      tags:
        - setup
        - galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
      tags:
        - setup
        - galaxy
    - role: usegalaxy_ca.maintenance
      tags:
        - setup
        - proxy
    - role: galaxyproject.nginx
      tags:
        - setup
        - proxy
    - role: laperlej.cvmfs
      tags:
        - setup
        - cvmfs
    - role: usegalaxy_ca.drmaa
      tags:
        - setup
    - role: usegalaxy_ca.restart_galaxy
      become: true
      become_user: root
      tags:
        - setup
        - galaxy
    - role: usegalaxy_ca.service_account
      become: false
      tags:
        - setup
        - galaxy
    - role: dj-wasabi.telegraf
      tags:
        - setup
        - monitor

  post_tasks:
    - name: fetch edugain idps the first time
      command: "bash {{ galaxy_root }}/server/cron/fetch-edugain-idps.bash"
      become: true
      become_user: pgalaxy
      tags:
        - setup
    - name: set cron jobs
      ansible.builtin.cron:
        name: "cron jobs to adjust allocations group for canadian users"
        minute: "*/5"
        user: pgalaxy
        job: "bash {{ galaxy_root }}/server/cron/set_new_users_allocation_groups.bash"
      tags:
        - setup

- hosts: monitorservers
  become: true
  become_user: root
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
    - pip:
        name: [docker, docker-compose]
        tags:
          - always
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - volume
        - monitor
        - nfs
        - setup
    - role: usegalaxy_ca.monitor
      tags:
        - monitor
        - setup
    - role: usegalaxy_ca.docker
      tags:
        - monitor
        - setup
    - role: usegalaxy_ca.influxdb_key
      tags:
        - monitor
        - setup
    - role: usegalaxy_eu.influxdb
      tags:
        - monitor
        - setup
    - role: cloudalchemy.grafana
      tags:
        - monitor
        - setup
    - role: dj-wasabi.telegraf
      tags:
        - setup
        - monitor
    - role: mvdbeek.sentry_selfhosted
      tags:
        - setup
        - monitor
    - role: usegalaxy_ca.backup_influx
      tags:
        - setup
        - monitor
    - role: usegalaxy_ca.backup_tsm
      tags:
        - setup
        - backup
