---
- hosts: galaxyservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
    - group_vars/terraform.yml
  pre_tasks:
    - name: install dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: galaxyproject.nginx
    - role: epigeec.volume
    - role: epigeec.setup
    - role: epigeec.postgresql
    - role: galaxyproject.postgresql
    - role: epigeec.restart_postgres
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    #   - role: epigeec.gxadmin
    #   - role: galaxyproject.gxadmin
    #   - role: epigeec.backup_pg
    - role: galaxyproject.repos
    - role: galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: "{{ galaxy_user_name }}"
    - role: epigeec.restart_galaxy
      become: true
      become_user: root
    - role: epigeec.service_account
      become: false

- hosts: datasetservers
  become: true
  become_user: root
  roles:
    - role: epigeec.docker
    - role: epigeec.dataset
