- hosts: galaxyservers
  become: true
  become_user: root
  vars:
    - slurm_roles: ["exec"]
  vars_files:
    - group_vars/slurm.yml
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name:
          [
            "acl",
            "bzip2",
            "git",
            "make",
            "tar",
            "python3-venv",
            "python3-setuptools",
          ]
      tags:
        - always
  roles:
    - role: galaxyproject.galaxy
      tags:
        - setup
        - galaxy

- hosts: monitorservers
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  roles:
    - role: usegalaxy_ca.volume
      tags:
        - volume
        - monitor
        - nfs
        - setup
    - role: usegalaxy_ca.docker
      tags:
        - monitor
        - setup
    - role: mvdbeek.sentry_selfhosted
      tags:
        - setup
        - monitor
